//
//  LandingRouter.swift
//  VIPTest
//
//  Created by Achem Samuel on 2/17/20.
//  Copyright (c) 2020 Achem Samuel. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol LandingRoutingLogic
{
  func routeToDetailScene(segue: UIStoryboardSegue?)
}

protocol LandingDataPassing
{
  var dataStore: LandingDataStore? { get }
}

class LandingRouter: NSObject, LandingRoutingLogic, LandingDataPassing
{
  weak var viewController: LandingViewController?
  var dataStore: LandingDataStore?
  
  // MARK: Routing
    func routeToDetailScene(segue: UIStoryboardSegue?) {
        let storyboard : UIStoryboard = UIStoryboard(name: DetailViewController.storyboardName, bundle: nil)
        let destinationVC = storyboard.instantiateViewController(withIdentifier: DetailViewController.STORYBOARD_ID) as! DetailViewController
        var destinationDS = destinationVC.router!.dataStore!
        destinationVC.interactor?.delegate = viewController?.interactor
        passDataToDetail(source: dataStore!, destination: &destinationDS)
        viewController?.present(destinationVC, animated: true, completion: nil)
    }
    
    func passDataToDetail(source: LandingDataStore, destination: inout DetailDataStore) {
        destination.User = source.User
        destination.userVm = source.userVm
    }
    
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
  
  //func navigateToSomewhere(source: LandingViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: LandingDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
