//
//  LandingPresenter.swift
//  VIPTest
//
//  Created by Achem Samuel on 2/17/20.
//  Copyright (c) 2020 Achem Samuel. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LandingPresentationLogic
{
    func presentDataOnLoad(response: Landing.fetchDataOnLoad.Response)
}
protocol LandingDisplayLogic: class
{
    func displayDataOnLoad(viewModel: Landing.fetchDataOnLoad.ViewModel)
}

class LandingPresenter: LandingPresentationLogic
{
  weak var viewController: LandingDisplayLogic?
  
    func presentDataOnLoad(response: Landing.fetchDataOnLoad.Response) {
        //print(response.user.age, response.user.name, response.user.familyName)
        let viewModel = Landing.fetchDataOnLoad.ViewModel(userViewModel: response.user.toviewModel()) //response converted to viewModel for the viewController's use
        viewController?.displayDataOnLoad(viewModel: viewModel)
    }
}
