//
//  LandingRouter.swift
//  VIPTest
//
//  Created by Achem Samuel on 2/17/20.
//  Copyright (c) 2020 Achem Samuel. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol LandingRoutingLogic
{
  func routeToDetailScene(segue: UIStoryboardSegue?)
}

protocol LandingDataPassing
{
  var dataStore: LandingDataStore? { get }
}

class LandingRouter: NSObject, LandingRoutingLogic, LandingDataPassing
{
  weak var viewController: LandingViewController?
  var dataStore: LandingDataStore?
  
  // MARK: Routing
    func routeToDetailScene(segue: UIStoryboardSegue?) {
        let storyboard : UIStoryboard = UIStoryboard(name: DetailViewController.storyboardName, bundle: nil)
        let destinationVC = storyboard.instantiateViewController(withIdentifier: DetailViewController.STORYBOARD_ID) as! DetailViewController
        var destinationDS = destinationVC.router!.dataStore!
        destinationVC.interactor?.delegate = viewController?.interactor
        passDataToDetail(source: dataStore!, destination: &destinationDS)
        viewController?.present(destinationVC, animated: true, completion: nil)
    }
    
    func passDataToDetail(source: LandingDataStore, destination: inout DetailDataStore) {
        //Both stores communicate with other and you share as much data as you would want to between them
        destination.User = source.User
        destination.userVm = source.userVm
    }
    
}
