//
//  DetailInteractor.swift
//  VIPTest
//
//  Created by Achem Samuel on 2/17/20.
//  Copyright (c) 2020 Achem Samuel. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DataDelegate: class {
    func passDataBack(user: user)
}

protocol DetailBusinessLogic
{
  var delegate: DataDelegate? { get set}
  func passBackUser()
}

protocol DetailDataStore
{
   
   var User: user? {get set}
   var userVm: UserViewModel {get set}
}

class DetailInteractor: DetailBusinessLogic, DetailDataStore
{
    var delegate: DataDelegate?
  var presenter: DetailPresentationLogic?  
 var userVm: UserViewModel = UserViewModel()
var User: user?

    
    func passBackUser() {
        guard let user = User else {return}
        delegate?.passDataBack(user: user)
    }
}
